# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tugas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.productLabel = QtWidgets.QLabel("Product", self.centralwidget)
        self.productLabel.setGeometry(QtCore.QRect(30, 30, 100, 20))
        
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 30, 200, 25))
        self.comboBox.addItems([
            "Bimoli (Rp. 20,000)", 
            "Beras 5 Kg (Rp. 75,000)",
            "Kecap ABC (Rp. 7,000)", 
            "Saos Saset (Rp. 2,500)"])
        
        self.quantityLabel = QtWidgets.QLabel("Quantity", self.centralwidget)
        self.quantityLabel.setGeometry(QtCore.QRect(30, 70, 100, 20))
        
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(130, 70, 60, 25))
        self.spinBox.setMinimum(1)
        
        self.discountLabel = QtWidgets.QLabel("Discount", self.centralwidget)
        self.discountLabel.setGeometry(QtCore.QRect(30, 110, 100, 20))
        
        self.discountBox = QtWidgets.QComboBox(self.centralwidget)
        self.discountBox.setGeometry(QtCore.QRect(130, 110, 60, 25))
        self.discountBox.addItems(["0%", "5%", "10%", "15%", "20%"])
        
        self.addButton = QtWidgets.QPushButton("Add to Cart", self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(30, 150, 120, 30))
        
        self.clearButton = QtWidgets.QPushButton("Clear", self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(160, 150, 80, 30))
        
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 200, 400, 120))
        
        self.totalLabel = QtWidgets.QLabel("Total: Rp. 0", self.centralwidget)
        self.totalLabel.setGeometry(QtCore.QRect(30, 330, 200, 20))
        
        self.errorLabel = QtWidgets.QLabel("", self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(30, 360, 200, 20))
        self.errorLabel.setStyleSheet("color: red;")

        self.identityLabel = QtWidgets.QLabel("Nabila Nur Syfani (F1D022082)", self.centralwidget)
        self.identityLabel.setGeometry(QtCore.QRect(30, 380, 300, 20))
        self.identityLabel.setStyleSheet("font-size: 8pt;")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.addButton.clicked.connect(self.add_to_cart)
        self.clearButton.clicked.connect(self.clear_cart)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def add_to_cart(self):
        product = self.comboBox.currentText()
        quantity = self.spinBox.value()
        discount = int(self.discountBox.currentText().replace('%', ''))

        if not product:  
            self.errorLabel.setText("Invalid input")
            return
        
        self.errorLabel.setText("")  

        price_dict = {
            "Bimoli (Rp. 20,000)": 20000,
            "Beras 5 Kg (Rp. 75,000)": 75000,
            "Kecap ABC (Rp. 7,000)": 7000,
            "Saos Saset (Rp. 2,500)": 2500,
        }
        price = price_dict.get(product, 0)
        total_price = price * quantity * (1 - discount / 100)
        
        cart_item = f"{product} - {quantity} x Rp. {price:,} (disc {discount}%)"
        self.listWidget.addItem(cart_item)
        
        current_total = int(self.totalLabel.text().split("Rp. ")[1].replace(",", ""))
        new_total = current_total + total_price
        self.totalLabel.setText(f"Total: Rp. {int(new_total):,}")
    
    def clear_cart(self):
        self.comboBox.setCurrentIndex(-1)  
        self.listWidget.clear()
        self.totalLabel.setText("Total: Rp. 0")
        self.errorLabel.setText("") 
    
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("POS Application")

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
